main project/src/BreastCancerDigitalAssistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('Ai-Advice/', include('tumor_prediction.urls')),
    path('questions/', include('questions.urls')),
    path('clinics/', include('clinics.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from schema_graph.views import Schema
urlpatterns += [
    # On Django 2+:
    path("schema/", Schema.as_view()),
]

main project/src/questions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #questions urls
    path('', views.list_questions, name="questions"),
    path('create/', views.create_question, name="question-create"),
    path('<int:pk>/', views.question_details, name="question-details"),
    path('update/<int:question_id>', views.update_question, name="update-question"),
    path('delete/<int:question_id>', views.delete_question, name="delete-question"),
    path('my-questions/', views.my_questions, name="my_questions"),

    # votes urls
    path('upvote/<int:answer_id>/<int:question_id>/', views.upvote, name="upvote"),
    path('downvote/<int:answer_id>/<int:question_id>/', views.downvote, name="downvote"),

    # answers urls
    path('add-answer/<int:question_id>', views.add_answer, name="add_answer"),
    path('update-answer/<int:answer_id>/<int:question_id>/', views.update_answer, name="update_answer"),
    path('delete-answer/<int:answer_id>/<int:question_id>/', views.delete_answer, name="delete_answer"),

    # search questions
    path('search/', views.search, name="questions-search"),
]

main project/src/users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('accounts/signup/', views.normal_user_signup, name='normal_user_signup'),
    path('accounts/signup/doctor/', views.doctor_signup, name='doctor_signup'),

    path('accounts/', include('allauth.urls')),
    path('profile/', views.user_profile, name="user_profile"),


    path('', views.home_page, name="home"),
    
    path('UA/', views.unauthorized, name="unauthorized")
]

main project/src/questions/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name



class Question(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    content = models.TextField()
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
    	return self.title



class Answer(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.answer


class UpVote(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} UpVote On {self.answer}"

class DownVote(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} DownVote On {self.answer}"

main project/src/questions/forms.py
from django.forms import ModelForm
from .models import Question, Answer

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content', 'tags']

class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['answer']

main project/src/questions/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Answer, Question, UpVote, DownVote
from .forms import QuestionForm, AnswerForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from users.decorators import doctor_required, normal_user_required
from django.db.models import Q
from django.views.decorators.http import require_http_methods


@require_http_methods(['GET'])
@login_required(login_url="account_login")
def list_questions(request):
    questions = Question.objects.all()
    
    context = {'questions': questions}
    return render(request, 'questions/index.html', context)



@require_http_methods(['GET', 'POST'])
@login_required(login_url="account_login")
@normal_user_required
def create_question(request):
    form = QuestionForm()
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('questions')

    context = {'form': form}
    return render(request, 'questions/QuestionForm.html', context)


@require_http_methods(['GET'])
@login_required(login_url="account_login")
def question_details(request, pk):
    question = get_object_or_404(Question, id=pk)
    answers = Answer.objects.filter(question=question).order_by("-created_at")
    answer_form = AnswerForm()
    context = {
        'question': question,
        'answers': answers,
        'answer_form': answer_form,
        
    }
    return render(request, 'questions/question_details.html', context)


@require_http_methods(['POST'])
@login_required(login_url="account_login")
@doctor_required
def add_answer(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    if request.user.is_normal_user:
        return render(request, 'questions/request_errors/request_unauthorized.html', status=401)
    if request.method == "POST":
        answer_form = AnswerForm(request.POST)
        if answer_form.is_valid():
            answer_form.instance.user = request.user
            answer_form.instance.question = question
            answer_form.save()
            messages.success(request, "Answer Added Successfuly.")
            return redirect("question-details", question.id)



@require_http_methods(['GET', 'POST', 'PUT'])
@login_required(login_url="account_login")
@normal_user_required
def update_question(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    if request.user.is_doctor:
        return render(request, 'questions/request_errors/request_unauthorized.html', status=401)
    if request.user==question.user:
        form = QuestionForm(instance=question)
        if request.method=="POST":
            form = QuestionForm(request.POST, instance=question)
            if form.is_valid():
                form.save()
                messages.success(request, "Question updated successfully.")
                return redirect('question-details', question_id)
    context = {
        'form': form
    }
    return render(request, 'questions/QuestionForm.html', context)



@require_http_methods(['GET', 'POST'])
@login_required(login_url="account_login")
@normal_user_required
def delete_question(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    if request.user == question.user:
        if request.method == "POST":
            question.delete()
            messages.success(request, "Question deleted successfully.")
            return redirect('questions')
    context = {
            'question': question,
            'question_id': question_id
        }
    return render(request, 'questions/delete_question.html', context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url="account_login")
def upvote(request, answer_id, question_id):
    answer = get_object_or_404(Answer, id=answer_id)
    user = request.user

    upvotes = UpVote.objects.filter(user=user, answer=answer)
    downvotes = DownVote.objects.filter(user=user, answer=answer)
    if (not downvotes):
        if request.method == "POST" and (not upvotes):
            upvote = UpVote(user=user, answer=answer)
            upvote.save()
            messages.success(request, "Answer Upvoted successfully.")
            return redirect("question-details", question_id)
        else:
            if request.method == "POST":
                user_vote = UpVote.objects.filter(user=user, answer=answer)
                user_vote.delete()
                messages.success(request, "Your Upvote deleted successfully.")
                return redirect("question-details", question_id)
    else:
        messages.info(request, "You downvoted this answer in order to upvote it, please delete your downvote first.")
        return redirect("question-details", question_id)            
    return redirect("question-details", question_id)
    


@require_http_methods(['GET', 'POST'])
@login_required(login_url="account_login")
def downvote(request, answer_id, question_id):
    answer = get_object_or_404(Answer, id=answer_id)
    user = request.user
    downvotes = DownVote.objects.filter(user=user, answer=answer)
    upvotes = UpVote.objects.filter(user=user, answer=answer)
    if (not upvotes):
        if request.method == "POST" and (not downvotes):
            downvote = DownVote(user=user, answer=answer)
            downvote.save()
            messages.success(request, "Answer Downvoted successfuly.")
            return redirect("question-details", question_id)
        else:
            if request.method == "POST":
                user_vote = DownVote.objects.filter(user=user, answer=answer)
                user_vote.delete()
                messages.success(request, "Your Downvote deleted successfully.")
                return redirect("question-details", question_id)
    else:
        messages.warning(request, "You upvoted this answer in order to downvote, it please delete your upvote first.")
        return redirect("question-details", question_id)           
    return redirect("question-details", question_id)



@require_http_methods(['GET', 'POST', 'PUT'])
@login_required(login_url="account_login")
@doctor_required
def update_answer(request, answer_id, question_id):
    
    answer = get_object_or_404(Answer, id=answer_id)
    form = AnswerForm(instance=answer)
    if request.method == "POST" and request.user == answer.user:
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            form.save()
            messages.success(request, "Your answer updated successfully.")
            return redirect("question-details", question_id)
    context = {
        'form': form,
        'question_id': question_id,
        }
    return render(request, 'questions/answer_form.html', context)



@require_http_methods(['GET', 'POST'])
@login_required(login_url="account_login")
@doctor_required
def delete_answer(request, answer_id, question_id):
    answer = get_object_or_404(Answer, id=answer_id)
    if request.method == "POST" and request.user == answer.user:
        answer.delete()
        messages.success(request, "Your answer deleted successfully.")
        return redirect("question-details", question_id)
    context = {
        'question_id': question_id,
    }    
    return render(request, 'questions/delete_answer.html', context)


@require_http_methods(['GET'])
@login_required(login_url="account_login")
def search(request):
    if request.method == "GET":
        query = request.GET.get('search_query', None)
        if query:
            questions = Question.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))
            
            context = {'questions':questions}
            return render(request, 'questions/question_search.html', context)
        return render(request, 'questions/question_search.html')


def my_questions(request):
    if request.user.is_normal_user:
        questions = Question.objects.filter(user=request.user)
    else: 
        return render(request, 'questions/request_errors/request_unauthorized.html')    

    context = {
        'questions':questions
    }
    return render(request, 'questions/my_questions.html', context)

main project/src/questions/templates/questions/QuestionForm.html
{% extends 'questions/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create Article</h1>
</div>

<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% endblock %}

main project/src/questions/templates/questions/answer_form.html
{% extends 'questions/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Update</button>
</form>
<a class="btn btn-secondary mt-1" href="{% url 'question-details' question_id %}">Cancel</a>
{% endblock %}

main project/src/questions/templates/questions/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Cards</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<body id="page-top" style="margin: 0; padding: 0;">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'questions/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form method="GET" action="{% url 'questions-search' %}"
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input name="search_query" type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - Alerts -->
                        

                        <!-- Nav Item - Messages -->
                        

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.username}}</span>
                                <img class="img-profile rounded-circle"
                                    src="{{request.user.profile.profile_img.url}}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'user_profile' %}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {% block content %}

                    
                    {% endblock %}

                    

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; BCCP 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'account_logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

main project/src/questions/templates/questions/delete_answer.html
{% extends 'users/dashboard/base.html' %}
{% block content %}
<div class="container">
    <h1>Are you sure you want to delete this answer?</h1>
    <p style="color: red;"><strong>Note: </strong>this action cannot be reversed</p>

    <form style="display: inline-block;" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    <a class="btn btn-secondary" href="{% url 'question-details' question_id %}">Cancel</a>

</div>
{% endblock %}

main project/src/questions/templates/questions/delete_question.html
{% extends 'users/dashboard/base.html' %}
{% block content %}
<div class="container">
    <h1>Are you sure you want to delete this Question?</h1>
    <p style="color: red;"><strong>Note: </strong>this action cannot be reversed</p>

    <form style="display: inline-block;" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    <a class="btn btn-secondary" href="{% url 'question-details' question_id %}">Cancel</a>

</div>
{% endblock %}

main project/src/questions/templates/questions/question_details.html
{% extends 'questions/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    body{
    margin-top:20px;
    background-color:#e9ebee;
}

.be-comment-block {
    margin-bottom: 50px !important;
    border: 1px solid #edeff2;
    border-radius: 2px;
    padding: 50px 70px;
    border:1px solid #ffffff;
}

.comments-title {
    font-size: 16px;
    color: #262626;
    margin-bottom: 15px;
    font-family: 'Conv_helveticaneuecyr-bold';
}

.be-img-comment {
    width: 60px;
    height: 60px;
    float: left;
    margin-bottom: 15px;
}

.be-ava-comment {
    width: 60px;
    height: 60px;
    border-radius: 50%;
}

.be-comment-content {
    margin-left: 80px;
}

.be-comment-content span {
    display: inline-block;
    width: 49%;
    margin-bottom: 15px;
}

.be-comment-name {
    font-size: 13px;
    font-family: 'Conv_helveticaneuecyr-bold';
}

.be-comment-content a {
    color: #383b43;
}

.be-comment-content span {
    display: inline-block;
    width: 49%;
    margin-bottom: 15px;
}

.be-comment-time {
    text-align: right;
}

.be-comment-time {
    font-size: 11px;
    color: #b4b7c1;
}

.be-comment-text {
    font-size: 13px;
    line-height: 18px;
    color: #7a8192;
    display: block;
    background: #f6f6f7;
    border: 1px solid #edeff2;
    padding: 15px 20px 20px 20px;
}

.form-group.fl_icon .icon {
    position: absolute;
    top: 1px;
    left: 16px;
    width: 48px;
    height: 48px;
    background: #f6f6f7;
    color: #b5b8c2;
    text-align: center;
    line-height: 50px;
    -webkit-border-top-left-radius: 2px;
    -webkit-border-bottom-left-radius: 2px;
    -moz-border-radius-topleft: 2px;
    -moz-border-radius-bottomleft: 2px;
    border-top-left-radius: 2px;
    border-bottom-left-radius: 2px;
}

.form-group .form-input {
    font-size: 13px;
    line-height: 50px;
    font-weight: 400;
    color: #b4b7c1;
    width: 100%;
    height: 50px;
    padding-left: 20px;
    padding-right: 20px;
    border: 1px solid #edeff2;
    border-radius: 3px;
}

.form-group.fl_icon .form-input {
    padding-left: 70px;
}

.form-group textarea.form-input {
    height: 150px;
}

</style>


<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">{{question.title}}</h6>
        <strong>Published at: {{question.created_at}}</strong>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Question Management:</div>
                <a class="dropdown-item" href="{% url 'question-details' question.id %}">Read More</a>
                <a class="dropdown-item" href="{% url 'update-question' question.id %}">Update</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'delete-question' question.id %}">Delete</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {{question.content}}
    </div>
    
</div>

<div>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <div class="container">
    <div class="be-comment-block">
        <h1 class="comments-title">Answers ({{answers.count}})</h1>
        {% for answer in answers %}
        <div class="be-comment">
            
            <div class="be-img-comment">	

                <a style="display: inline-block;" href="#">
                    <img src="{{answer.user.profile.profile_img.url}}" alt="" class="be-ava-comment">
                </a>
                
            </div>
            
            <div class="be-comment-content">
                
                    <span class="be-comment-name">
                        <strong style="font-size: 20px">{{answer.user}}</strong>
                        </span>
                    <span class="be-comment-time">
                        <i class="fa fa-clock-o"></i>
                        {{answer.created_at}}
                    </span>
                    
                    <div class="row">                    
                    {% if request.user == answer.user %}
                        <div class="col-2">
                            <a href="{% url 'delete_answer' answer.id question.id %}" style="display: inline-block;"><span class="material-icons">delete_forever</span></a>
                            <a href="{% url 'update_answer' answer.id question.id %}"><span class="material-icons">update</span></a>
                        </div>
                
                    {% endif %}
                    <hr>
                    </div> 
                    <div class="row">
                        <div class="col-3">
                            <form method="POST" action="{% url 'upvote' answer.id question.id %}" style="display: inline-block;">
                                {% csrf_token %}<strong>{{answer.upvote_set.all.count}}</strong><button style="border: none; background-color: white;" class="m-auto" type="submit"><span class="material-icons">thumb_up</span></button>
                            </form>
                            <form method="POST" action="{% url 'downvote' answer.id question.id %}" style="display: inline-block;">
                                {% csrf_token %}<strong>{{answer.downvote_set.all.count}}</strong><button style="border: none; background-color: white;" class="m-auto" type="submit"><span class="material-icons">thumb_down</span></button>
                            </form>
                        </div>
                    </div>
                <p style="font-size: 20px;" class="be-comment-text">
                   {{answer.answer}}
                </p>

            </div>
        </div>
        <hr>
        {% endfor %}
        {% if request.user.is_doctor %}
        <form method="POST" action="{% url 'add_answer' question.id %}" class="form-block">
                {% csrf_token %}
                {{answer_form|crispy}}
            
                <input class="btn btn-primary" type="submit" value="Submit"/>
        </form>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}